sudo: required
dist: trusty
language: c
before_script:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
  - sudo apt-add-repository -y ppa:flabbergast/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y --force-yes astyle flabbergast-java devscripts groff man-db xmlstarlet texlive-binaries equivs
  - sudo mk-build-deps -i -t "apt-get -qq -y --force-yes --no-install-recommends"
script: "./.travis-build"
notifications:
  on_success: never
  on_failure: change
deploy:
  provider: s3
  access_key_id: AKIAJY7JELRUQJ6ESEWA
  secret_access_key: zp+y+ChONJCjH7NA3juWJHTh7mOVnlpVSlrpW+2h0bFFS1IGwQ9Zdtplfxjf3zwycEj1bYYWSYM5ORbi5G0zAxsnfqoVMWVrUpPpfuoYwSuBPVMkDWuQ1zZSMnhVT0rDB4jBnamoYV9W1c4sT62i64CgjIhxzgza9lnnF74qhuI=
  bucket: docs.flabbergast.org
  skip_cleanup: true
  local_dir: www
