sudo: required
dist: trusty
language: c
before_script:
  - sudo apt-add-repository -y ppa:flabbergast/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y --force-yes astyle flabbergast-java devscripts equivs
  - sudo mk-build-deps -i -t "apt-get -qq -y --force-yes --no-install-recommends"
script: "./bootstrap && ./autogen.sh && ./configure && make && make check && ./check-format"
notifications:
  on_success: never
  on_failure: change
