sudo: required
dist: trusty
language: c
before_script:
  - sudo apt-add-repository -y ppa:flabbergast/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y --force-yes flabbergast-java devscripts equivs
  - sudo mk-build-deps -i
script: "./bootstrap && ./autogen.sh && ./configure && make && make check"
notifications:
  on_success: never
  on_failure: change
